### PR TITLE
fix(components): show no data message for prevalence over time

### LINKED ISSUE #502: Prevalence over time: crash when no data
The component crashes when LAPIS returns no data for the specified filter:
* Go to the "One Dataset" story (http://localhost:6006/?path=/story/visualization-prevalence-over-time--one-dataset)
* Change `numeratorFilter.lapisFilter.dateFrom` to `2025-10-01`

Result:
grafik
Browser console:
grafik

The error disappears when I set the smoothingWindow to 0.

### PR DESCRIPTION
**Pull request by JonasKellerer**
Resolves #502

### Summary
Adds a guard against missing data. It then shows "No data available". Also fixes the error, that when no data is returned the sliding window still works.

Moreover, a general guard was introduced to each of the charts (bar, line, bubble), so they don't throw an error, when they get no data.

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx [hunk 1]
```diff
@@ -30,12 +31,18 @@ const PrevalenceOverTimeBarChart = ({
...
+        .map((variantData) => {
+            return {
+                content: variantData.content.sort(sortNullToBeginningThenByDate),
+                displayName: variantData.displayName,
+            };
+        });
+
+    if (nullFirstData.length === 0) {
+        return <NoDataDisplay />;
+    }
```
Comment (fengelniederhammer) [inline components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx:45]: What data do I need to have to get into this early return? I wasn't able to find anything?

**Review by fengelniederhammer — APPROVED** [review]

File: components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx (hunk 1 above)
Comment (JonasKellerer) [reply components/src/preact/prevalenceOverTime/prevalence-over-time-bar-chart.tsx:45]: The main point was to avoid calling `nullFirstData[0]`, when there is nothing inside. This case can occur, when the denominator filter returns an empty array. The filter step above filters for that case.
