### PR TITLE
fix(components): gs-date-range-selector: validate component attributes

### LINKED ISSUE #557: gs-date-range-selector: validate input

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #557

### Summary

This is a proof of concept how we can use zod to validate component attributes.

### Screenshot

grafik

### PR Checklist

- [x] All necessary documentation has been adapted.
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: components/src/preact/components/error-display.tsx [hunk 1]
```diff
@@ -115,5 +125,21 @@ function getDisplayedErrorMessage(error: Error) {
         };
     }
 
+    if (error instanceof InvalidPropsError) {
+        const firstError = error.zodError.errors[0];
+        let message = error.zodError.issues
+            .map((issue) => `Unexpected value for "${issue.path}": ${issue.message}`)
```
Comment (JonasKellerer) [inline components/src/preact/components/error-display.tsx:131]:
```suggestion
           .map((issue) => {
                // eslint-disable-next-line @typescript-eslint/ban-ts-comment
                // @ts-expect-error
                return `Unexpected value "${JSON.stringify(error.componentProps[issue.path])}" for "${issue.path}": ${issue.message}`;
            })
```
It would be nice to show also the value, which is wrong. I did not find a better solution, than to use the "ts-expect-error".

File: components/src/preact/components/error-display.tsx [hunk 2]
```diff
@@ -24,9 +25,16 @@ export class UserFacingError extends Error {
     }
 }
 
+export class InvalidPropsError extends Error {
+    constructor(public readonly zodError: ZodError) {
+        super(zodError.message);
+        this.name = 'InvalidPropsError';
+    }
+}
+
```
Comment (JonasKellerer) [inline components/src/preact/components/error-display.tsx:34]:
```suggestion
export class InvalidPropsError extends Error {
    constructor(public readonly zodError: ZodError, public readonly componentProps: unknown) {
        super(zodError.message);
        this.name = 'InvalidPropsError';
    }
}
```
See comment below.

**Review by JonasKellerer — APPROVED** [review]
Nice. Good to have. 

Maybe we also show what is the conflicting value?
