### PR TITLE
fix(components): make annotation list scrollable

### LINKED ISSUE #1011: mutations over time: 'Filter mutations' popup doesn't handle long list of annotations well
https://github.com/user-attachments/assets/b13ed1ec-a16e-4444-bb1a-86087d589dec

Probably should be a scroll list or something

### PR DESCRIPTION
**Pull request by fhennig**
resolves #1011

### Summary

Add an `overflow-scroll`.

Not very happy with the test, maybe we could also just remove it, not sure if we even need a test here. I wanted to check that initially the last annotation isn't visible, then you scroll, and then it is, but I couldn't get it done.

### Screenshot

https://github.com/user-attachments/assets/f9c65db4-a79f-4d7a-87bf-6e948f7852a6

### PR Checklist

- ~~All necessary documentation has been adapted.~~ 
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: components/src/preact/components/mutations-over-time-mutations-filter.tsx [hunk 1]
```diff
@@ -105,34 +105,36 @@ const AnnotationCheckboxes: FunctionComponent<MutationsOverTimeMutationsFilterPr
...
-                                            annotationNameFilter: new Set(newAnnotationFilter),
-                                        };
-                                    });
-                                }}
-                            />
-                            {annotation.name} (<span className='text-red-600'>{annotation.symbol}</span>)
-                        </label>
-                    </li>
-                ))}
+                <div className='h-72 overflow-scroll'>
```
Comment (fengelniederhammer) [inline components/src/preact/components/mutations-over-time-mutations-filter.tsx]:
```suggestion
                <div className='max-h-72 overflow-scroll'>
```
