### PR TITLE
fix(components): mutation over time worker runs on message change

### LINKED ISSUE #509: Controls don't work on mutation over time webcomponent storybook
When on the web component storybook, nothing changes when users change the controls of the component. This should be fixed.

### PR DESCRIPTION
**Pull request by JonasKellerer**
Resolves #509

### Summary
Fixes the bug, that the mutation over time component in storybook does not update on controls change

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

File: components/src/preact/mutationsOverTime/mutations-over-time.tsx [hunk 1]
```diff
@@ -63,15 +63,21 @@ export const MutationsOverTimeInner: FunctionComponent<MutationsOverTimeProps> =
...
-        new MutationOverTimeWorker() as Worker,
+        };
+    }, [granularity, lapis, lapisDateField, lapisFilter, sequenceType]);
+
+    const workerProvider = useCallback(() => new MutationOverTimeWorker() satisfies Worker, []);
+
+    const { data, error, isLoading } = useWebWorker<MutationOverTimeQuery, MutationOverTimeWorkerResponse>(
+        messageToWorker,
+        workerProvider,
     );
```
Comment (fengelniederhammer) [inline components/src/preact/mutationsOverTime/mutations-over-time.tsx:81]: I think we can do even better by reusing the same worker:

```suggestion
    const worker = useMemo(() => new MutationOverTimeWorker(), []);

    const { data, error, isLoading } = useWebWorker<MutationOverTimeQuery, MutationOverTimeWorkerResponse>(
        messageToWorker,
        worker,
    );
```

This requires splitting the `useEffect` in `useWebWorker` in two parts:
```
    useEffect(() => {
        worker.onmessage = ...
        worker.onmessageerror = ...

        // no return!
    }, [worker]);

    useEffect(() => {
        worker.postMessage(messageToWorker);
    }, [messageToWorker, worker]);
```

**Review by fengelniederhammer — APPROVED** [review]

**Comment by fengelniederhammer** [comment]
And please add the issue that this resolves to the commit message

**Comment by JonasKellerer** [comment]
> And please add the issue that this resolves to the commit message (in the footer so that release please picks it up)

Just for future reference: The "resolves" or "refs" message must be the last line of the commit message.
