### PR TITLE
fix(components): make it possible to copy an annotated mutation in Firefox

### LINKED ISSUE #778: Mutation annotations: the annotated mutations should not be a button
They should be some sort of text so that you can copy them. Firefox doesn't let me copy the text content of a button (In Chrome it works though).

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #778

### Summary

Apparently Firefox doesn't let you copy the content of a button.
### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

File: components/src/preact/components/annotated-mutation.tsx [hunk 1]
```diff
@@ -63,18 +63,21 @@ const AnnotatedMutationWithoutContext: FunctionComponent<AnnotatedMutationWithou
     );
 
     return (
-        <ButtonWithModalDialog modalContent={modalContent} modalRef={modalRef}>
```
Comment (JonasKellerer) [inline components/src/preact/components/annotated-mutation.tsx:66]: I think `buttonClassName={'select-text'}` would do the same (at least i can copy it from firefox). Does this work for you as well?

Comment (fengelniederhammer) [reply components/src/preact/components/annotated-mutation.tsx:66]: Nice. Thanks :)

**Review by JonasKellerer — APPROVED** [review]
