### PR TITLE
fix(components): gs-mutations: validate attributes

### LINKED ISSUE #573: gs-mutations: validate input

### PR DESCRIPTION
**Pull request by JonasKellerer**
Resolves: #573 

### Summary

Added the validation of the input and slighly adjust the filter description.

### PR Checklist

~~- [ ] All necessary documentation has been adapted.~~
~~- [ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

File: components/src/preact/mutations/mutations.tsx [hunk 1]
```diff
@@ -28,31 +29,37 @@ import { type DisplayedSegment, SegmentSelector, useDisplayedSegments } from '..
 import Tabs from '../components/tabs';
 import { useQuery } from '../useQuery';
 
+const viewSchema = z.union([z.literal('table'), z.literal('grid'), z.literal('insertions')]);
 export type View = 'table' | 'grid' | 'insertions';
```
Comment (fengelniederhammer) [inline components/src/preact/mutations/mutations.tsx:33]: Let's also reuse `views` from the `types.ts`.

File: components/src/preact/mutations/mutations.tsx [hunk 2]
```diff
@@ -28,31 +29,37 @@ import { type DisplayedSegment, SegmentSelector, useDisplayedSegments } from '..
...
 
-export interface MutationsProps {
-    width: string;
-    height: string;
-    lapisFilter: LapisFilter;
-    sequenceType: SequenceType;
-    views: View[];
-    pageSize: boolean | number;
-}
+const MutationsInnerPropsSchema = z.object({
```
Comment (fengelniederhammer) [inline components/src/preact/mutations/mutations.tsx:35]: I think we don't need separate "inner" props - we have to pass all props down to the info component anyway.

**Review by fengelniederhammer — CHANGES_REQUESTED** [review]

**Review by fengelniederhammer — APPROVED** [review]
